INSERT INTO category (id,title)
VALUES
    (1,'COMPUTER_SCIENCE'), (2,'ELECTRONICS'), (3,'ELECTRICAL_ENGINEERING'), (4,'MECHANICS'), (5,'TELECOMMUNICATIONS'),
    (6,'ARCHITECTURAL_ENGINEERING'), (7,'ENERGETICS'), (8,'BIOTECHNOLOGY'), (9,'CHEMICAL_ENGINEERING'), (10,'MATERIAL_ENGINEERING'),
    (11,'GEODESY_AND_CARTOGRAPHY'), (12,'CHEMISTRY'), (13,'MATHS'), (14,'PHYSICS'), (15,'ENVIRONMENTAL_ENGINEERING'),
    (16,'GEOPHYSICS'), (17,'AGRICULTURAL_ENGINEERING'), (18,'MANUFACTURING_ENGINEERING'), (19,'METALLURGY'), (20,'BIOPHYSICS');