services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  db-test:
    image: postgres
    restart: always
    ports:
      - 5442:5442
    environment:
      POSTGRES_DB: test_postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025